apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cicd-apps
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-clusterrolebinding
subjects:
  - kind: User
    name: system:serviceaccount:infrastructure:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cicd-apps
  apiGroup: rbac.authorization.k8s.io