master:
  image: jenkinsci/blueocean
  imageTag: latest
  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - backup
    - slack
    - artifactory
    - google-login
    - jobConfigHistory
    - http_request
  javaOpts: "-Xms150m -Xmx300m -Dkubernetes.websocket.ping.interval=30"
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: jenkins.dev.webtree.org
    path: /
  tolerations: {}
  resources:
    request:
      cpu: "10m"
    limits:
      cpu: "500m"
  nodeSelector:
    "node-role.kubernetes.io/type": backend
  healthProbesLivenessTimeout: 240
  healthProbesReadinessTimeout: 120
agent:
  enabled: true
  resources:
    request:
      cpu: "100m"
    limits:
      cpu: "200m"
      memory: "300Mi"
  nodeSelector:
    "node-role.kubernetes.io/type": backend
persistence:
  enable: true
  existingClaim: jenkins-volume
  size: 5Gi
networkPolicy:
  apiVersion: networking.k8s.io/v1
rbac:
  create: true
serviceAccount:
  name: jenkins-cd
  create: true