Master:
  Image: jenkinsci/blueocean
  ImageTag: latest
  InstallPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - backup
    - slack
    - artifactory
  JavaOpts: "-Xms1000m -Xmx1000m"
  ServiceType: ClusterIP
  ingress:
    enabled: true
    hostName: jenkins.dev.webtree.org
    path: /
  Tolerations: {}
  resources:
    request:
      cpu: "0"
  NodeSelector:
    wt-type: backend
Agent:
  Enabled: true
  resources:
    request:
      cpu: "10m"
    limits:
      cpu: "50m"
      memory: "512Mi"
  NodeSelector:
    wt-type: backend
Persistence:
  Size: 5Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins